### ISSUE TITLE
Revenue and Cost

### ISSUE THREAD

**Issue by arjunmehta94** [arjunmehta94/BSFC#1]
Create Revenue and Cost 

Revenue calculation:
- start with payments (possibly also need to factor in tip amounts)
- expand by tender
    - For tenders, 
        - check label for `store use` and `spoilage` and `food prep`and subtract from total
        - Otherwise, simply add the amount (currently assuming that discounts are accounted for in total revenue). If not, we need to add `unitQty/1000 * price` for any item sold by units to the total, or simply add the `price` to the total for singleton items.
 
Total cost: 
#9 being done by @katherinelatimer2013

**Comment by katherinelatimer2013** [comment]
Also: for calculating total cost, we would ideally do that by category (expansion field of "item" called "categories") -- e.g., of our total costs for the month of $1,000, $500 was for produce, $200 was for bulk, $300 was for bakery, etc.

**Comment by arjunmehta94** [comment]
@katherinelatimer2013 Is that different from simply adding costs of all items? Or do you mean have the calculation also show the category totals?

**Comment by katherinelatimer2013** [comment]
@arjunmehta94 The latter.
